const lyricGenerator = {
  SET_LYRIC_SOURCE: "SET_LYRIC_SOURCE",
  SET_LYRIC_SCHEMA: "SET_LYRIC_SCHEMA",
  SET_LYRIC_SOURCE_FILTER_CHARS: "SET_LYRIC_SOURCE_FILTER_CHARS",
  SET_STANZA_PATTERN: "SET_STANZA_PATTERN",
  SET_STANZA_OPTIONS: "SET_STANZA_OPTIONS",
  SET_GENERATED_LYRICS: "SET_GENERATED_LYRICS",
};

export default lyricGenerator;
