const page = {
  SET_MODAL: "SET_MODAL",
  SET_BODY_TYPE: "SET_BODY_TYPE",
  SET_HEADER_TYPE: "SET_HEADER_TYPE",
  SET_LOADING: "SET_LOADING",
  SET_INFORMATION: "SET_INFORMATION",
  SET_TIME_LEFT: "SET_TIME_LEFT",
  SET_TIMER_PLAYING: "SET_TIMER_PLAYING",
  SET_TIMER_HANDLE: "SET_TIMER_HANDLE",
  SET_ACTIVE_STEP: "SET_ACTIVE_STEP",
  SET_STEPS: "SET_STEPS",
};

export default page;
