const stanzaOptions = {
  V1: {
    id: "V1",
    lines: [
      {
        syllables: 8,
        accents: [true, false, true, false, true, false, true, false],
        rhyme: "A",
        endsSentence: false,
      },
      {
        syllables: 12,
        accents: [
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
        rhyme: "B",
        endsSentence: true,
      },
      {
        syllables: 8,
        accents: [true, false, true, false, true, false, true, false],
        rhyme: "A",
        endsSentence: false,
      },
      {
        syllables: 12,
        accents: [
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
        rhyme: "B",
        endsSentence: true,
      },
      {
        syllables: 6,
        accents: [true, false, false, false, true, false],
        rhyme: "C",
        endsSentence: true,
      },
      {
        syllables: 4,
        accents: [true, false, false, false],
        rhyme: "C",
        endsSentence: true,
      },
    ],
  },
  V2: {
    id: "V2",
    lines: [
      {
        syllables: 8,
        accents: [true, false, true, false, true, false, true, false],
        rhyme: "A",
        endsSentence: false,
      },
      {
        syllables: 12,
        accents: [
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
        rhyme: "B",
        endsSentence: true,
      },
      {
        syllables: 8,
        accents: [true, false, true, false, true, false, true, false],
        rhyme: "A",
        endsSentence: false,
      },
      {
        syllables: 12,
        accents: [
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
        rhyme: "B",
        endsSentence: true,
      },
      {
        syllables: 6,
        accents: [true, false, false, false, true, false],
        rhyme: "C",
        endsSentence: true,
      },
      {
        syllables: 4,
        accents: [true, false, false, false],
        rhyme: "C",
        endsSentence: true,
      },
    ],
  },
  C: {
    id: "C",
    lines: [
      {
        syllables: 8,
        accents: [true, false, true, false, true, false, true, false],
        rhyme: "D",
        endsSentence: false,
      },
      {
        syllables: 8,
        accents: [true, false, true, false, true, false, true, false],
        rhyme: "D",
        endsSentence: false,
      },
      {
        syllables: 4,
        accents: [true, false, false, false, true, false],
        rhyme: "E",
        endsSentence: true,
      },
      {
        syllables: 4,
        accents: [true, false, false, false],
        rhyme: "E",
        endsSentence: true,
      },
    ],
  },
  B: {
    id: "B",
    lines: [
      {
        syllables: 6,
        accents: [true, false, false, false, true, false],
        rhyme: "F",
        endsSentence: false,
      },
      {
        syllables: 4,
        accents: [true, false, false, false],
        rhyme: "G",
        endsSentence: true,
      },
      {
        syllables: 6,
        accents: [true, false, false, false, true, false],
        rhyme: "F",
        endsSentence: false,
      },
      {
        syllables: 4,
        accents: [true, false, false, false],
        rhyme: "G",
        endsSentence: true,
      },
    ],
  },
};

export default stanzaOptions;
